// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-case.cuh"

#if !defined(GGML_USE_MUSA)
DECL_FATTN_MMA_KVARN_CASE(128, 128, 64, 1);
DECL_FATTN_MMA_KVARN_CASE(256, 256, 64, 1);
DECL_FATTN_MMA_KVARN_CASE(512, 512, 64, 1);
#endif
